name: Build Vulkan Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_wheels_vulkan:
    name: Vulkan Wheels
    uses: ./.github/workflows/build-wheels-vulkan-full.yml
    with:
      version: ${{ inputs.version }}
      config: 'rename:1'
