name: Build Everything TGW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.14'
        default: 'v0.2.14'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_wheels_vulkan:
    name: Vulkan Wheels
    uses: ./.github/workflows/build-wheels-oobabooga-vulkan.yml
    with:
      version: ${{ inputs.version }}
